spring.application.name=cv-generator

#Configuración de la base de datos MySQl
spring.datasource.url=jdbc:mysql://localhost:3306/cv_generator_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=springuser
spring.datasource.password=miclave123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuración de MySQL (para Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Mostrar SQL en consola
spring.jpa.show-sql=true
#DDL automático (update crea/actualiza tablas según las entidades)
spring.jpa.hibernate.ddl-auto=update
#Formatear SQL para mejor lectura
spring.jpa.properties.hibernate.format_sql=true

#Mostrar parámetros de las consultas SQL (nivel DEBUG para Hibernate)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Cambiar puerto de la aplicación (por defecto 8080)
server.port=8090